openapi: "3.0.1"
info:
  description: "This is the API for each instance of the Key/Value Service"
  version: "1.0.0"
  title: "Key/Value Service"

paths:
  /keys/{key}:
    get:
      description: "Get the value for the key"
      parameters:
        - in: path
          name: key
          schema:
            type: string
          required: true
      responses:
        200:
          description: "The value for the requested key"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemArray'
        404:
          description: "The key does not exist"
    post:
      parameters:
        - in: path
          name: key
          schema:
            type: string
          required: true

      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/PutSchema'
                - $ref: '#/components/schemas/AppendSchema'


      responses:
        204:
          description: "The value for the requested key"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemArray'

        400:
          description: "The request is not valid"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Error'



  /admin/status:
    get:
      description: "Get the node status"
      responses:
        200:
          description: "The node status"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Status'
        500:
          description: "The status cannot be obtained"


components:
  schemas:
    Status:
      type: string
    Item:
      type: string
    ItemArray:
      type: array
      items:
        $ref: '#/components/schemas/Item'
    PutSchema:
      type: object
      properties:
        type:
          type: string
          enum:
            - PUT
        value:
          $ref: '#/components/schemas/ItemArray'
    AppendSchema:
      type: object
      properties:
        type:
          type: string
          enum:
            - APPEND
        value:
          $ref: '#/components/schemas/Item'
    Error:
      type: string






